name: Greetings

on:
  pull_request:
    types: created
  issues:
    types: created

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, thank you for making your first issue! Please be as elaborate as possible, such as sharing the reproduction steps!'
        pr-message: 'Hey, thank you for making your first PR! Please make sure you ran ktlint, you can do so by running the ktlintFormat gradle task.'
