name: Run code inspections and testing

on:
  # Make sure we run inspections only if kotlin files are updated
  push:
    branches:
      - master
      - 'releases/**'
    paths:
      - '**.kt'
      - '**.kts'
  pull_request:
    paths:
      - '**.kt'
      - '**.kts'

jobs:
  # First setup the environment so we can work with it
  setup:
    name: Setup for the inspections
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Display artifact files
        run: ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: discord-kt
          path: ./

  # Run KtLinter
  ktlint:
    name: Runs the KtLinter inspections
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          - name: discord-kt

      - name: Run ktlinter
        run: ./gradlew ktlintCheck

  # Run JUnit
  junit:
    name: Runs the JUnit tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          - name: discord-kt

      - name: Run tests
        run: ./gradlew clean test
